---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-ddbctl-job
spec:
  template:
    spec:
      containers:
      - name: ddbctl-container
        image: jittakal/go-dynamodb-partition-delete:latest
        command: ["/ddbctl", "delete-partition"]
        args:
          - "-t"
          - "{{ .Values.ddbCtlJob.tableName }}"
          - "-p"
          - "{{ .Values.ddbCtlJob.partitionValue }}"
          - "-e"
          - "{{ .Values.ddbCtlJob.endpointURL }}"
          - "-r"
          - "{{ .Values.ddbCtlJob.awsRegion }}"
          - "-s"
        # Optionally, you can add environment variables here if needed
      restartPolicy: Never
